name: Docker Image CI

on:
  push:
    branches: [master]
    paths:
      - "backend/**"
      - "!backend/tests/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install Heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - name: heroku deploy
        working-directory: backend/
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API }}
        run: |
          heroku container:login
          heroku container:push web -a osint-backend
          heroku container:release web -a osint-backend
