name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
        (
        echo "${{ secrets.HEROKU_EMAIL }}"
        echo "${{ secrets.HEROKU_API }}"
        ) | heroku login --interactive
        docker login --username=_ --password=$(heroku auth:token) registry.heroku.com
#    - name: Build the Docker image
#      working-directory: backend/
#      run: docker build . --file Dockerfile --tag osint-backend:latest
    - name: Push image to heroku
      #env:
      #  HEROKU_API_KEY: ${{ secrets.HEROKU_API }}
      working-directory: backend/
      run: heroku container:push web -a osint-backend
    - name: deploy application
      #env:
      #  HEROKU_API_KEY: ${{ secrets.HEROKU_API }}
      working-directory: backend/ 
      run: heroku container:release web -a osint-backend
